version: '3.4'
networks:
  restaurant:
    driver: bridge

services:
  postgres:
    container_name: restaurant-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: restaurant-redis
    image: redis:7-alpine
    ports:
      - '6379:6349'
    volumes:
      - redis-data:/data

  api:
    container_name: restaurant-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3000:3000'

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local